### ISSUE TITLE
Add multiple responses

### ISSUE THREAD

**Issue by MXWest** [brianmoran/mockify#3]
Allow for multiple responses. For example, on 1st call to an endpoint provide response[0], the second response[1] etc. and simply starting over at the end of the list to allow for multiple kinds of response (successes and failures).

**Comment by p4tin** [comment]
As you send 1 response I would just remove it from the list - also you can think about a default response be set and that is sent back always unless you have a "special" response in the list to send.

**Comment by brianmoran** [comment]
@p4tin @MXWest - I added in the ability to return multiple responses. I used a map that returns a response based on the method and URI. So a `GET` to `/helloworld/foo` returns a different response than a `GET` to `/helloworld/bar` with `/helloworld/{key}` being the pattern matcher to the request handler.
