### ISSUE TITLE
Update image on Docker Hub

### ISSUE THREAD

**Issue by jwanglof** [brianmoran/mockify#35]
@brianmoran 
Can you please update the Docker Hub image (https://hub.docker.com/r/brianmoran/mockify/tags) for this project?

Would be nice to be able to remove my fork for this image that have the feature I need :)

**Comment by brianmoran** [comment]
@jwanglof - The image has been updated. 

Sorry for the delay. Life has been busy and I haven't been able to do much with mockify.
